import classes.Utils

// Vanilla
Utils.removeItem(item('minecraft:gold_ore'))
Utils.removeItem(item('minecraft:iron_ore'))
Utils.removeItem(item('minecraft:coal_ore'))
Utils.removeItem(item('minecraft:lapis_ore'))
Utils.removeItem(item('minecraft:diamond_ore'))
Utils.removeItem(item('minecraft:redstone_ore'))
Utils.removeItem(item('minecraft:emerald_ore'))
Utils.removeItem(item('minecraft:quartz_ore'))
Utils.removeItem(item('minecraft:quartz_ore'))

// AE2
Utils.removeItem(item('appliedenergistics2:material:51'))
Utils.removeItem(item('appliedenergistics2:material:49'))
Utils.removeItem(item('appliedenergistics2:material:3'))
Utils.removeItem(item('appliedenergistics2:material:3'))
Utils.removeItem(item('appliedenergistics2:material:2'))
Utils.removeItem(item('appliedenergistics2:material:46'))
Utils.removeItem(item('appliedenergistics2:material:46'))
Utils.removeItem(item('appliedenergistics2:material:40'))
Utils.removeItem(item('appliedenergistics2:material:5'))
Utils.removeItem(item('appliedenergistics2:material'))
Utils.removeItem(item('appliedenergistics2:material:12'))

// Agricraft
Utils.removeItem(item('agricraft:agri_nugget'))
Utils.removeItem(item('agricraft:agri_nugget', 1))
Utils.removeItem(item('agricraft:agri_nugget', 2))
Utils.removeItem(item('agricraft:agri_nugget', 3))
Utils.removeItem(item('agricraft:agri_nugget', 4))
Utils.removeItem(item('agricraft:agri_nugget', 5))
Utils.removeItem(item('agricraft:agri_nugget', 6))
Utils.removeItem(item('agricraft:agri_nugget', 7))
Utils.removeItem(item('agricraft:agri_nugget', 8))
Utils.removeItem(item('agricraft:agri_nugget', 9))
Utils.removeItem(item('agricraft:agri_nugget', 10))
Utils.removeItem(item('agricraft:agri_nugget', 11))
Utils.removeItem(item('agricraft:agri_nugget', 12))

// Biomes o' Plenty
Utils.removeItem(item('biomesoplenty:gem_block', 7))
Utils.removeItem(item('biomesoplenty:gem', 7))
Utils.removeItem(item('biomesoplenty:gem_ore', 7))

// Ender IO
Utils.removeItem(item('enderio:item_material', 30))
Utils.removeItem(item('enderio:item_material', 74))
Utils.removeItem(item('enderio:item_material:9'))
Utils.removeItem(item('enderio:item_material:10'))
Utils.removeItem(item('enderio:item_alloy_ingot'))

// Extra Planets
Utils.removeItem(item('extraplanets:ingot_mercury'))
Utils.removeItem(item('extraplanets:ingot_lead'))
Utils.removeItem(item('extraplanets:tier4_items', 5))
Utils.removeItem(item('extraplanets:ingot_uranium'))
Utils.removeItem(item('extraplanets:tier5_items', 5))
Utils.removeItem(item('extraplanets:tier5_items', 7))
Utils.removeItem(item('extraplanets:tier6_items', 5))
Utils.removeItem(item('extraplanets:tier8_items', 5))
Utils.removeItem(item('extraplanets:tier9_items', 5))
Utils.removeItem(item('extraplanets:tier10_items', 5))

// Forestry
Utils.removeItem(item('forestry:ingot_copper'))
Utils.removeItem(item('forestry:ingot_tin'))
Utils.removeItem(item('forestry:ingot_bronze'))
Utils.removeItem(item('forestry:gear_bronze'))
Utils.removeItem(item('forestry:gear_copper'))
Utils.removeItem(item('forestry:gear_tin'))
Utils.removeItem(item('forestry:ash'))
Utils.removeItem(item('forestry:apatite'))
Utils.removeItem(item('forestry:resources'))
Utils.removeItem(item('forestry:resources', 1))
Utils.removeItem(item('forestry:resources', 2))
Utils.removeItem(item('forestry:resource_storage'))
Utils.removeItem(item('forestry:resource_storage', 1))
Utils.removeItem(item('forestry:resource_storage', 2))
Utils.removeItem(item('forestry:resource_storage', 3))

// Galacticraft
Utils.removeItem(item('galacticraftcore:basic_item:2'))
Utils.removeItem(item('galacticraftcore:basic_item:3'))
Utils.removeItem(item('galacticraftcore:basic_item:4'))
Utils.removeItem(item('galacticraftcore:basic_item:5'))
Utils.removeItem(item('galacticraftcore:ic2compat'))
Utils.removeItem(item('galacticraftcore:item_basic_moon'))
Utils.removeItem(item('galacticraftcore:basic_block_moon'))
Utils.removeItem(item('galacticraftcore:basic_block_moon', 1))
Utils.removeItem(item('galacticraftcore:basic_block_core', 5))
Utils.removeItem(item('galacticraftcore:basic_block_core', 6))
Utils.removeItem(item('galacticraftcore:basic_block_core', 7))
Utils.removeItem(item('galacticraftcore:basic_block_core', 9))
Utils.removeItem(item('galacticraftcore:basic_block_core', 10))
Utils.removeItem(item('galacticraftcore:basic_block_core', 11))
Utils.removeItem(item('galacticraftcore:basic_block_core', 13))

Utils.removeItem(item('galacticraftplanets:asteroids_block', 7))
Utils.removeItem(item('galacticraftplanets:venus', 12))
Utils.removeItem(item('galacticraftplanets:mars', 8))
Utils.removeItem(item('galacticraftplanets:mars', 2))
Utils.removeItem(item('galacticraftplanets:item_basic_mars'))
Utils.removeItem(item('galacticraftplanets:item_basic_asteroids'))
Utils.removeItem(item('galacticraftplanets:item_basic_asteroids:9'))
Utils.removeItem(item('galacticraftplanets:basic_item_venus:1'))

// Thaumcraft
Utils.removeItem(item('thaumcraft:ingot', 2))
Utils.removeItem(item('thaumcraft:metal_brass'))
Utils.removeItem(item('thaumcraft:nugget'))
Utils.removeItem(item('thaumcraft:nugget', 1))
Utils.removeItem(item('thaumcraft:nugget', 2))
Utils.removeItem(item('thaumcraft:nugget', 3))
Utils.removeItem(item('thaumcraft:nugget', 4))
Utils.removeItem(item('thaumcraft:nugget', 8))
Utils.removeItem(item('thaumcraft:plate'))
Utils.removeItem(item('thaumcraft:plate', 1))
Utils.removeItem(item('thaumcraft:plate', 2))
Utils.removeItem(item('thaumcraft:plate', 3))
Utils.removeItem(item('thaumcraft:ore_amber'))
Utils.removeItem(item('thaumcraft:amber_block'))

// Tinkers Construct
Utils.removeItem(item('tconstruct:ingots'))
Utils.removeItem(item('tconstruct:ingots', 5))
Utils.removeItem(item('tconstruct:nuggets'))
Utils.removeItem(item('tconstruct:nuggets', 5))
Utils.removeItem(item('tconstruct:metal'))
Utils.removeItem(item('tconstruct:metal', 5))
Utils.removeItem(item('tconstruct:ore'))
Utils.removeItem(item('tconstruct:ore', 1))