// Machines
crafting.removeByOutput(item('enderio:block_simple_sag_mill'))
crafting.removeByOutput(item('enderio:block_sag_mill'))
crafting.removeByOutput(item('enderio:block_enhanced_sag_mill'))
crafting.removeByOutput(item('enderio:block_vat'))
crafting.removeByOutput(item('enderio:block_enhanced_vat'))
crafting.removeByOutput(item('enderio:block_combustion_generator'))
crafting.removeByOutput(item('enderio:block_enhanced_combustion_generator'))
crafting.removeByOutput(item('enderio:block_simple_stirling_generator'))
crafting.removeByOutput(item('enderio:block_stirling_generator'))

mods.jei.hideCategory('AlloySmelter')
mods.jei.hideCategory('CombustionGenerator')
mods.jei.hideCategory('SagMill')
mods.jei.hideCategory('GrindingBall')
mods.jei.hideCategory('StirlingGenerator')
mods.jei.hideCategory('EIOWC')
mods.jei.hideCategory('EIOWO')
mods.jei.hideCategory('EIOWO')

mods.enderio.sag_mill.removeAll()
mods.enderio.fluid_fuel.removeAll()
mods.enderio.fluid_coolant.removeAll()
mods.enderio.alloy_smelter.removeAll()